# file: jupyter_config.yaml

jupyterhub:
  singleuser:
    cpu:
      limit: 4
      guarantee: 1
    memory:
      limit: 14G
      guarantee: 4G

  # this section specifies the IP address for pangeo
  proxy:
    service:
      loadBalancerIP: <GCE_EXTERNAL_IP>
